<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="loginTest"
    errors="1" failures="0" hostname="" id="" package="loginTest" skipped="0"
    tests="1" time="0.04100" timestamp="Thu, 15 Mar 2018 04:58:51 GMT">
  
    <testcase name="Verify that a user cannot login with no valid input" classname="loginTest" time="0.04100" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Login Test / Verify that a user cannot login with no valid input]:

  ReferenceError: login is not defined
    at Object.VerifyThatAUserCannotLoginWithNoValidInput [as Verify that a user cannot login with no valid input] (/home/danny/Documents/SapnaTesting/tests/loginTest.js:21:5)
    at Module.call (/home/danny/Documents/SapnaTesting/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /home/danny/Documents/SapnaTesting/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/home/danny/Documents/SapnaTesting/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/danny/Documents/SapnaTesting/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/danny/Documents/SapnaTesting/node_modules/q/q.js:796:13)
    at /home/danny/Documents/SapnaTesting/node_modules/q/q.js:556:49
    at runSingle (/home/danny/Documents/SapnaTesting/node_modules/q/q.js:137:13)
    at flush (/home/danny/Documents/SapnaTesting/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
